name: Playwright Tests
on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug
#      test:
#        description: 'True to print to STDOUT'
#        required: true
#        type: boolean
#      tags:
#        description: 'Test scenario tags'
#        required: true
#        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Display the info
      run: |
        echo "Log Level: ${{ github.event.inputs.logLevel }}"
        echo "Environment: ${{ github.event.inputs.environment }}"
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: Playwright Report
        path: playwright-report/
        retention-days: 30
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: Allure Report
        path: allure-results/
        retention-days: 30
